AUTOMAKE_OPTIONS = foreign

glucatincludedir = $(includedir)/glucat
glucatinclude_HEADERS = \
	clifford_algebra.h \
	clifford_algebra_imp.h \
	errors.h \
	errors_imp.h \
	framed_multi.h \
	framed_multi_imp.h \
	generation.h \
	generation_imp.h \
	global.h \
	glucat.h \
	glucat_config.h \
	glucat_imp.h \
	index_set.h \
	index_set_imp.h \
	long_double.h \
	matrix.h \
	matrix_arma.h \
	matrix_arma_imp.h \
	matrix_base.h \
	matrix_base_imp.h \
	matrix_eigen.h \
	matrix_eigen_imp.h \
	matrix_imp.h \
	matrix_multi.h \
	matrix_multi_imp.h \
	portability.h \
	promotion.h \
	qd.h \
	random.h \
	scalar.h \
	scalar_imp.h \
	tuning.h

AM_CPPFLAGS = $(all_includes) $(GLUCAT_CPPFLAGS)
DISTCLEANFILES = glucat_config.h
